#pragma once
#include <juce_audio_basics/juce_audio_basics.h>
#include <cmath>
#include <array>

/**
 * PadSynth — Simple built-in pad synthesizer.
 *
 * Converts the MIDI events generated by the engine into warm pad audio.
 * Uses layered detuned saw/sine oscillators with a slow attack envelope
 * and built-in reverb-like tail via feedback delay.
 *
 * This makes CaptainDrift a self-contained instrument:
 * just load it and press play.
 */
class PadSynth
{
public:
    static constexpr int kMaxSynthVoices = 16;

    PadSynth();

    void prepare (double sampleRate, int blockSize);
    void reset();

    /** Process MIDI events and generate audio into the buffer. */
    void processBlock (juce::AudioBuffer<float>& audioBuffer,
                       const juce::MidiBuffer& midiBuffer);

private:
    struct SynthVoice
    {
        bool active = false;
        int noteNumber = -1;
        int channel = 0;
        float velocity = 0.0f;

        // Oscillator phases
        double phase1 = 0.0;   // Main sine
        double phase2 = 0.0;   // Detuned sine +
        double phase3 = 0.0;   // Detuned sine -
        double phase4 = 0.0;   // Sub octave

        // Frequency
        double baseFreq = 440.0;
        double pitchBendFactor = 1.0;

        // Envelope
        float envelope = 0.0f;
        bool releasing = false;
        float releaseLevel = 0.0f;
        float releasePhase = 0.0f;
    };

    double sampleRate = 44100.0;

    std::array<SynthVoice, kMaxSynthVoices> voices;

    // Per-channel pitch bend (channels 1-8 for our 8 generative voices)
    std::array<double, 16> channelPitchBend;

    // Simple lowpass state for warmth
    float lpState[2] = { 0.0f, 0.0f };

    // Envelope parameters
    static constexpr float kAttackRate  = 0.0003f;   // Slow attack (~3s to full)
    static constexpr float kReleaseRate = 0.0001f;    // Very slow release (~10s)
    static constexpr float kDetuneCents = 8.0f;       // Detune amount

    void noteOn (int channel, int note, float velocity);
    void noteOff (int channel, int note);
    void handlePitchBend (int channel, int bendValue);
    float renderVoice (SynthVoice& voice);
    double midiNoteToFreq (int note) const;
};
